# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/frederik/Dropbox/Speciale/Bose Hubbard ITensor"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/frederik/Dropbox/Speciale/Bose Hubbard ITensor"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/frederik/Dropbox/Speciale/Bose Hubbard ITensor/CMakeFiles" "/home/frederik/Dropbox/Speciale/Bose Hubbard ITensor/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/frederik/Dropbox/Speciale/Bose Hubbard ITensor/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyLib

# Build rule for target.
MyLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyLib
.PHONY : MyLib

# fast build rule for target.
MyLib/fast:
	$(MAKE) -f CMakeFiles/MyLib.dir/build.make CMakeFiles/MyLib.dir/build
.PHONY : MyLib/fast

#=============================================================================
# Target rules for targets named BoseHubbardCondensateFraction

# Build rule for target.
BoseHubbardCondensateFraction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BoseHubbardCondensateFraction
.PHONY : BoseHubbardCondensateFraction

# fast build rule for target.
BoseHubbardCondensateFraction/fast:
	$(MAKE) -f CMakeFiles/BoseHubbardCondensateFraction.dir/build.make CMakeFiles/BoseHubbardCondensateFraction.dir/build
.PHONY : BoseHubbardCondensateFraction/fast

#=============================================================================
# Target rules for targets named BoseHubbard

# Build rule for target.
BoseHubbard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BoseHubbard
.PHONY : BoseHubbard

# fast build rule for target.
BoseHubbard/fast:
	$(MAKE) -f CMakeFiles/BoseHubbard.dir/build.make CMakeFiles/BoseHubbard.dir/build
.PHONY : BoseHubbard/fast

main/BoseHubbard.o: main/BoseHubbard.cpp.o

.PHONY : main/BoseHubbard.o

# target to build an object file
main/BoseHubbard.cpp.o:
	$(MAKE) -f CMakeFiles/BoseHubbard.dir/build.make CMakeFiles/BoseHubbard.dir/main/BoseHubbard.cpp.o
.PHONY : main/BoseHubbard.cpp.o

main/BoseHubbard.i: main/BoseHubbard.cpp.i

.PHONY : main/BoseHubbard.i

# target to preprocess a source file
main/BoseHubbard.cpp.i:
	$(MAKE) -f CMakeFiles/BoseHubbard.dir/build.make CMakeFiles/BoseHubbard.dir/main/BoseHubbard.cpp.i
.PHONY : main/BoseHubbard.cpp.i

main/BoseHubbard.s: main/BoseHubbard.cpp.s

.PHONY : main/BoseHubbard.s

# target to generate assembly for a file
main/BoseHubbard.cpp.s:
	$(MAKE) -f CMakeFiles/BoseHubbard.dir/build.make CMakeFiles/BoseHubbard.dir/main/BoseHubbard.cpp.s
.PHONY : main/BoseHubbard.cpp.s

main/BoseHubbardCondensateFraction.o: main/BoseHubbardCondensateFraction.cpp.o

.PHONY : main/BoseHubbardCondensateFraction.o

# target to build an object file
main/BoseHubbardCondensateFraction.cpp.o:
	$(MAKE) -f CMakeFiles/BoseHubbardCondensateFraction.dir/build.make CMakeFiles/BoseHubbardCondensateFraction.dir/main/BoseHubbardCondensateFraction.cpp.o
.PHONY : main/BoseHubbardCondensateFraction.cpp.o

main/BoseHubbardCondensateFraction.i: main/BoseHubbardCondensateFraction.cpp.i

.PHONY : main/BoseHubbardCondensateFraction.i

# target to preprocess a source file
main/BoseHubbardCondensateFraction.cpp.i:
	$(MAKE) -f CMakeFiles/BoseHubbardCondensateFraction.dir/build.make CMakeFiles/BoseHubbardCondensateFraction.dir/main/BoseHubbardCondensateFraction.cpp.i
.PHONY : main/BoseHubbardCondensateFraction.cpp.i

main/BoseHubbardCondensateFraction.s: main/BoseHubbardCondensateFraction.cpp.s

.PHONY : main/BoseHubbardCondensateFraction.s

# target to generate assembly for a file
main/BoseHubbardCondensateFraction.cpp.s:
	$(MAKE) -f CMakeFiles/BoseHubbardCondensateFraction.dir/build.make CMakeFiles/BoseHubbardCondensateFraction.dir/main/BoseHubbardCondensateFraction.cpp.s
.PHONY : main/BoseHubbardCondensateFraction.cpp.s

src/correlations.o: src/correlations.cpp.o

.PHONY : src/correlations.o

# target to build an object file
src/correlations.cpp.o:
	$(MAKE) -f CMakeFiles/MyLib.dir/build.make CMakeFiles/MyLib.dir/src/correlations.cpp.o
.PHONY : src/correlations.cpp.o

src/correlations.i: src/correlations.cpp.i

.PHONY : src/correlations.i

# target to preprocess a source file
src/correlations.cpp.i:
	$(MAKE) -f CMakeFiles/MyLib.dir/build.make CMakeFiles/MyLib.dir/src/correlations.cpp.i
.PHONY : src/correlations.cpp.i

src/correlations.s: src/correlations.cpp.s

.PHONY : src/correlations.s

# target to generate assembly for a file
src/correlations.cpp.s:
	$(MAKE) -f CMakeFiles/MyLib.dir/build.make CMakeFiles/MyLib.dir/src/correlations.cpp.s
.PHONY : src/correlations.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... MyLib"
	@echo "... rebuild_cache"
	@echo "... BoseHubbardCondensateFraction"
	@echo "... BoseHubbard"
	@echo "... main/BoseHubbard.o"
	@echo "... main/BoseHubbard.i"
	@echo "... main/BoseHubbard.s"
	@echo "... main/BoseHubbardCondensateFraction.o"
	@echo "... main/BoseHubbardCondensateFraction.i"
	@echo "... main/BoseHubbardCondensateFraction.s"
	@echo "... src/correlations.o"
	@echo "... src/correlations.i"
	@echo "... src/correlations.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

