#!/bin/bash

gnuplot fig.g
latex fig.tex
dvips fig.dvi
rm -f fig.eps
ps2eps fig.ps
epspdf fig.eps
rm -f fig.tex
rm -f fig.dvi
rm -f fig.ps
rm -f fig.eps
rm -f fig-inc.eps
rm -f fig.log
rm -f fig.aux
rm -f texput.log
